[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]
[font]
size = 12.0

[font.normal]
family = "JetbrainsMono Nerd Font"

[window]
opacity = 1.0

[window.padding]
x = 10
y = 10
